version: 0.2

phases:
  pre_build:
    commands:
      - echo "Fetching parameters from Parameter Store..."
      - API_URL=$(aws ssm get-parameter --name /regulus/prod/API_URL --with-decryption --query Parameter.Value --output text)
      - DATABASE_URL=$(aws ssm get-parameter --name /regulus/prod/DATABASE_URL --with-decryption --query Parameter.Value --output text)
      - INSTANCE_ID=$(aws ssm get-parameter --name /regulus/prod/INSTANCE_ID --with-decryption --query Parameter.Value --output text)
      - REGION=$(aws ssm get-parameter --name /regulus/prod/REGION --with-decryption --query Parameter.Value --output text)
      - JWT_EXPIRATION=$(aws ssm get-parameter --name /regulus/prod/JWT_EXPIRATION --with-decryption --query Parameter.Value --output text)
      - JWT_SECRET=$(aws ssm get-parameter --name /regulus/prod/JWT_SECRET --with-decryption --query Parameter.Value --output text)
      - LOG_LEVEL=$(aws ssm get-parameter --name /regulus/prod/LOG_LEVEL --with-decryption --query Parameter.Value --output text)
      - NODE_ENV=$(aws ssm get-parameter --name /regulus/prod/NODE_ENV --with-decryption --query Parameter.Value --output text)
      - echo "INSTANCE_ID=$INSTANCE_ID"
      - echo "REGION=$REGION"
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin 841467961522.dkr.ecr.eu-west-1.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build --no-cache -t regulus .
      - docker tag regulus:latest 841467961522.dkr.ecr.eu-west-1.amazonaws.com/regulus:latest
  post_build:
    commands:
        - echo "Pushing the Docker image to Amazon ECR..." 
        - echo "Fetching EC2 Public IP..."
        - PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids $INSTANCE_ID \
            --query "Reservations[0].Instances[0].PublicIpAddress" \
            --output text --region $REGION)
        - echo "Public IP is $PUBLIC_IP"
        - API_URL=http://$PUBLIC_IP:3000
        - echo "API_URL is $API_URL"
        - echo "Deploying the Docker container to EC2 via SSM..."
        - |
          aws ssm send-command \
            --instance-ids $INSTANCE_ID \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Docker container" \
            --parameters '{"commands":["aws ecr get-login-password --region '$REGION' | docker login --username AWS --password-stdin 841467961522.dkr.ecr.eu-west-1.amazonaws.com",
                                        "docker pull 841467961522.dkr.ecr.eu-west-1.amazonaws.com/regulus:latest",
                                        "docker stop regulus-container || true",
                                        "docker rm regulus-container || true",
                                        "docker run -d --name regulus-container -p 3000:3000 -e API_URL='$API_URL' 841467961522.dkr.ecr.eu-west-1.amazonaws.com/regulus:latest"]}' \
            --region $REGION

artifacts:
  files:
    - "**/*"
  discard-paths: yes
